export const REQ_MANY = 'STUDY_INBOX_REQ_MANY';
export const RES_MANY = 'STUDY_INBOX_RES_MANY';
export const REQ_ONE = 'STUDY_INBOX_REQ_ONE';
export const RES_ONE = 'STUDY_INBOX_RES_ONE';
export const REQ_UPDATE_ONE = 'STUDY_INBOX_REQ_UPDATE_ONE';
export const RES_UPDATE_ONE = 'STUDY_INBOX_RES_UPDATE_ONE';
export const REQ_DELETE_ONE = 'STUDY_INBOX_REQ_DELETE_ONE';
export const RES_DELETE_ONE = 'STUDY_INBOX_RES_DELETE_ONE';