env:
  - dev
  - prod
dir:
  assets: "/assets"
  assetsSass: "/assets/sass"
  assetsJade: "/assets/jade"
  assetsImg: "/assets/img"
  assetsFont: "./assets/font"
  build:  "/build"
  src: "/src"
  devCss: "/tmp/css"
  buildCss: "/build/css"
  buildImg: "/build/img"
  buildFont: "./build/font"
file:
  clientConfig: "config.json"
gulp:
  compass:
    http_path: "/webpack-dev-server"
  image:
    optimizationLevel: 0
webpack:
  entry:
    - "./src/index.jsx"
  output:
    path: "./build"
    publicPath: "/"
    filename: "bundle.js"
  module:
    loaders:
      # json loader
      - test: ".json$"
        include: "./src"
        loader: "json"
      # jsx loader
      - test: ".jsx?$"
        include:
          - "./src"
          - "./node_modules/react-circular-progress"
        loader: "babel"
      # sass loader
      - test: ".scss$"
        include:
          - "./src/components"
        loader: "style!css!sass"
  resolve:
    extensions:
      - ""
      - ".js"
      - ".jsx"
  devServer:
    hot: false
    contentBase: "./build"
  plugins:
    hasHotModuleReplacement: false
  # config for sass-loader
  sassLoader:
client:
  api:
    protocol: http
    host: localhost
    port: 8081
  models:
    Test:
      pathname: /tests