webpack:
  entry:
    - "webpack-dev-server/client?http://localhost:8080"
    - "webpack/hot/only-dev-server"
    - "./src/index.jsx"
  output:
    path: "./build"
    publicPath: "/"
    filename: "bundle.js"
  module:
    loaders:
      # json loader
      - test: ".json$"
        include: "./src"
        loader: "json"
      # jsx loader
      - test: ".jsx?$"
        include:
          - "./src"
          - "./node_modules/react-circular-progress"
        loader: "babel"
      # sass loader
      - test: ".scss$"
        include:
          - "./src/components"
        loader: "style!css!sass"
  resolve:
    extensions:
      - ""
      - ".js"
      - ".jsx"
  devServer:
    hot: true
  plugins:
    hasHotModuleReplacement: true